runtime: java
env: flex
handlers:
  - url: /.*
    script: this field is required, but ignored
    
env_variables:
	MYSQL_DSN:mysql:unix_soquet=/cloudsql/ejercicio-23people:us-central1:school;dbname=school
	MYSQL_USER:chriss
	MYSQL_PASSWORD:962154